PRJ_NAME    := engine
PRJ_BRANCH  := 1.0
PRJ_VERSION := $(PRJ_BRANCH).0
PRJ_TYPE    := lib
PRJ_LIB_TYPE:= dynamic
PRJ_DEPENDENCIES := ../01-lib-battery

TEST_DEFINES = -DEXIT_ON_ERROR

include ../../Makefile
